### PR TITLE
use lighter version of HtmlEncode

### PR DESCRIPTION
**Pull request by nneeoo**
We can use stringbuilder to encode strings that is not part of markup, removing unnecessary allocations.
I registered almost 3x perf improvement in some scenarios on my machine.

Implemented as per RFC:
https://datatracker.ietf.org/doc/html/rfc1866#section-3.2.1

### CODE REVIEW

**Comment by Lanayx** [comment]
@nneeoo Can you please fix failing cases

**Comment by Lanayx** [comment]
I've also found that the perf is almost 2 times slower compared to WebUtility in the following benchmark:

```fsharp
    let testText = (Seq.init 10000 (fun _ -> "Some long error text")) |> String.concat ";"
    
    [<Benchmark>]
    member this.WebUtility() =
        let sb = StringBuilder()
        WebUtility.HtmlEncode testText
        |> sb.Append
        |> ignore

    [<Benchmark>]
    member this.Tools() =
        let sb = StringBuilder()
        Tools.HtmlEncode sb testText
 ```
 
 ```
 | Method     | Mean     | Error   | StdDev  | Gen0     | Gen1     | Gen2     | Allocated |
|----------- |---------:|--------:|--------:|---------:|---------:|---------:|----------:|
| WebUtility | 174.1 us | 1.35 us | 1.06 us | 124.7559 | 124.7559 | 124.7559 | 410.34 KB |
| Tools      | 280.1 us | 5.47 us | 7.84 us |  51.7578 |  34.1797 |        - | 424.78 KB |
```

**Comment by nneeoo** [comment]
@Lanayx, i fixed failed test and found space for perf improvements, probably. Maybe. Idk. At least on my machine. 
Same benchmark as yours.
```
BenchmarkDotNet v0.14.0, Windows 10 (10.0.19045.5011/22H2/2022Update)
Intel Core i9-9900K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET SDK 8.0.403
  [Host]     : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2 DEBUG
  DefaultJob : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2


| Method     | Mean     | Error    | StdDev   | Median   | Gen0     | Gen1     | Gen2     | Allocated |
|----------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|----------:|
| WebUtility | 327.0 us | 11.48 us | 33.86 us | 337.6 us | 124.7559 | 124.7559 | 124.7559 | 410.34 KB |
| Tools      | 264.7 us |  2.49 us |  2.33 us | 264.4 us |  51.7578 |  34.1797 |        - | 424.78 KB |
```

**Comment by Lanayx** [comment]
Thanks! Here is how it looks on my machine:

```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.4391/23H2/2023Update/SunValley3)
AMD Ryzen 5 5600H with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.403
  [Host]     : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2 DEBUG
  DefaultJob : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2


| Method     | Mean     | Error   | StdDev  | Gen0     | Gen1     | Gen2     | Allocated |
|----------- |---------:|--------:|--------:|---------:|---------:|---------:|----------:|
| WebUtility | 167.0 us | 1.13 us | 1.00 us | 111.0840 | 110.8398 | 110.8398 | 411.18 KB |
| Tools      | 434.0 us | 3.07 us | 2.56 us |  51.7578 |  34.1797 |        - | 424.78 KB |
```

I'll try to figure out why there is such a difference.

**Comment by Lanayx** [comment]
BTW, I've updated the test suite and it's still failing

**Comment by Lanayx** [comment]
@nneeoo I think it's because current algorithm is ineffective, haveUnencodedChars returns true with your code and false in WebUtility code. I recommend translating the library algorithm as is.

**Review by Lanayx — APPROVED** [review]

**Pull request merged**
