### PR TITLE
Add GitHubActions CI job

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by Lanayx** [comment]
@knocte Thank! Can you please point it to develop branch?

**Comment by knocte** [comment]
I liked your Oxpecker blog post, you're going in the right direction when changing some things from Giraffe!

But I disagree about not using a master/main branch :) It is confusing. Main development should go to main/master branch, like in Giraffe.

**Comment by Lanayx** [comment]
@knocte main branch is used! However, it's used for making releases out of it, not for direct commits - the difference with develop is that all project references are substituted with nuget references. Also, the release commits are tagged in master branch, not in develop branch. Also, it worth mentioning that this exactly follows Giraffe contributing rules!
image

**Comment by knocte** [comment]
> it worth mentioning that this exactly follows Giraffe contributing rules!

Fair enough, I thought it was a difference because you have set the defqault branch to be `develop`, while Giraffe's default is still master. Anyway, I disagree about this way of doing things, but who am I to argue... changing branch now.

**Review by Lanayx — APPROVED** [review]

**Comment by Lanayx** [comment]
Thanks a lot! I'll keep in mind you comment regarding branches, so if other people will also complain, we can review the branching strategy again.

**Pull request merged**
