### PR TITLE
Use fantomas to check the code

### PR DESCRIPTION
**Pull request by 64J0**
## Description:

With this PR, I'm adding a new CI workflow to check the code using fantomas.

- Close https://github.com/Lanayx/Oxpecker/issues/1.

You can look at how it works on CI here: https://github.com/64J0/Oxpecker/pull/1.

image

---

Please let me know if you'd like me to change something in this PR so it could be merged.

### CODE REVIEW

**Comment by Lanayx** [comment]
I'm not sure, but tend to think that is shouldn't be a separate action, rather integrated into existing CI workflow, what do you think?

**Comment by 64J0** [comment]
> I'm not sure, but tend to think that is shouldn't be a separate action, rather integrated into existing CI workflow, what do you think?

This is a valid option. I'll merge them soon!

> Can you please also merge latest changes

Sure.

**Comment by 64J0** [comment]
Do you prefer to use the same job that is there (build), or to add the fantomas validation as a separate job @Lanayx ?

**Comment by Lanayx** [comment]
I actually don't have strong opinion on that. Having them in one job is fine, separating dotnet tool in another job also makes sense. So merging it as you made it :)

**Pull request merged**
